name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - run: git config --global user.name 'cammytang'
      - run: git config --global user.email 'cammy.tang@endeavorstreaming.com'

      - name: release patch
        if: "startsWith(github.event.head_commit.message, 'fix: ')"
        run: npm version patch -m "[RELEASE] %s"

      - name: release minor
        if: "startsWith(github.event.head_commit.message, 'feat: ')"
        run: npm version minor -m "[RELEASE] %s"

      - name: release major
        if: "startsWith(github.event.head_commit.message, 'feat!: ')"
        run: npm version major -m "[RELEASE] %s"

      - run: git push
